### ISSUE TITLE
Error: Unexpected keyword 'false'

### ISSUE THREAD

**Issue by davecyen** [r3dm/warning#49]
I'm receiving the following error when trying to run my build script with vite:

```
Unexpected keyword 'false' (17:4) in /node_modules/warning/warning.js
file: /node_modules/warning/warning.js:17:4

15:  */
16:
17: var __DEV__ = process.env.NODE_ENV !== 'production';
        ^
18:
19: var warning = function() {};
```

**Comment by BerkeleyTrue** [comment]
Not familiar with vite. Sounds like you might have some config that blindly goes through and replaces __DEV__ with `false`. So you end up with `var false = process.env.NODE_ENV !== 'production';`

This may be a systematic issue with Vite since it should be smart enough to know that `var _DEV_ = ....` is an assignment and not a read of a var (i.e. `if (__DEV__)`). 

This is just a quick comment. Might be more to it.

**Comment by BerkeleyTrue** [comment]
Closing as not an issue with this module. If you find out the solution to your problem please feel free to post here so others who come upon this issue tracker can know as well.
